version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - CKAD
  - Falco
  - gvisor
  - kata
  - KCNA
  - KCSA
  - KodeKloud
  - kubeadm
  - kubelet
  - kubesec
  - Kubestronaut
  - Kustomize
  - seccomp
  - Trivy
  - Udemy
ignoreWords: []
import: []
